finnhub:
  base-url: ${FINNHUB_URL:https://finnhub.io/api/v1}
  token: ${FINNHUB_TOKEN}

spring:
  application.name: finance-trading

  cloud.openfeign:
    client:
      config:
        default:
          connect-timeout: 3000
          read-timeout: 10000
          loggerLevel: basic
          dismiss404: true

  datasource:
    url: ${FINANCE_DB_URL}
    username: ${FINANCE_DB_USER}
    password: ${FINANCE_DB_PASSWORD}
    hikari:
      connection-timeout: 200000
      max-lifetime: 500000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
      discovery:
        enabled: false
    access:
      default: none
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      access: read_only
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState, diskSpace, db
server:
  port: 8080
  address: 0.0.0.0